spring.application.name=Deepak

server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/DemoDB
spring.datasource.username=postgres
spring.datasource.password=Tiamed!!
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update